name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn install and build
      run: |
        yarn
        yarn build
      env:
        CI: true
    - name: Yarn Package Publish
      uses: luvies/action-yarn-publish@v0.1.1
      with:
        # The path to the root directory containing the package.json.
        # package-path: # optional
        # If set to true, all actions that would have been performed are skipped.
        # dry-run: # optional, default is false
        # A semver string of the versions to skip publishing of (see https://npm.im/semver for syntax).
        # skipped-versions: # optional
        # Whether to also tag the current commit with the version.
        git-tag: true # optional, default is false
        # The format the git tag should use ({version} is replaced by the package.json version).
        # git-tag-format: # optional, default is v{version}
