name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Yarn install
      run: yarn
      env:
        CI: true
    - name: Yarn build   
      run: yarn build
      env:
        CI: true
    - name: Yarn publish     
      run: yarn publish --non-interactive --access public
#     - name: Yarn Package Publish
#       uses: luvies/action-yarn-publish@v0.1.1
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         # The path to the root directory containing the package.json.
#         # package-path: # optional
#         # If set to true, all actions that would have been performed are skipped.
#         # dry-run: # optional, default is false
#         # A semver string of the versions to skip publishing of (see https://npm.im/semver for syntax).
#         # skipped-versions: # optional
#         # Whether to also tag the current commit with the version.
#         git-tag: true # optional, default is false
#         # The format the git tag should use ({version} is replaced by the package.json version).
#         # git-tag-format: # optional, default is v{version}
